### ISSUE TITLE
mongo split brain

### ISSUE THREAD

**Issue by buhe** [smartsdk/mongo-rs-controller-swarm#24]
Good Project, we test on my dev env and running sometimes, mongo_controller found logs :
```
pymongo.errors.OperationFailure: Our config version of 292623 is no larger than the version on 10.0.0.4:27017, which is 317746
mongo_controller.1.nbj7ikkuufy0@srmbuffer010210212018.sqa.ztt    | INFO:__main__:Mongo service is up and running
mongo_controller.1.nbj7ikkuufy0@srmbuffer010210212018.sqa.ztt    | INFO:__main__:Primary is: 10.0.0.3
mongo_controller.1.nbj7ikkuufy0@srmbuffer010210212018.sqa.ztt    | INFO:__main__:To add: {'10.0.0.4'}
mongo_controller.1.nbj7ikkuufy0@srmbuffer010210212018.sqa.ztt    | Traceback (most recent call last):
mongo_controller.1.nbj7ikkuufy0@srmbuffer010210212018.sqa.ztt    |   File "/src/replica_ctrl.py", line 314, in <module>
mongo_controller.1.nbj7ikkuufy0@srmbuffer010210212018.sqa.ztt    |     manage_replica(mongo_service, **envs)
mongo_controller.1.nbj7ikkuufy0@srmbuffer010210212018.sqa.ztt    |   File "/src/replica_ctrl.py", line 281, in manage_replica
mongo_controller.1.nbj7ikkuufy0@srmbuffer010210212018.sqa.ztt    |     update_config(primary_ip, current_member_ips, new_member_ips, mongo_port)
mongo_controller.1.nbj7ikkuufy0@srmbuffer010210212018.sqa.ztt    |   File "/src/replica_ctrl.py", line 234, in update_config
mongo_controller.1.nbj7ikkuufy0@srmbuffer010210212018.sqa.ztt    |     res = cli.admin.command("replSetReconfig", config, force=force)
mongo_controller.1.nbj7ikkuufy0@srmbuffer010210212018.sqa.ztt    |   File "/usr/local/lib/python3.6/site-packages/pymongo/database.py", line 532, in command
mongo_controller.1.nbj7ikkuufy0@srmbuffer010210212018.sqa.ztt    |     codec_options, session=session, **kwargs)
mongo_controller.1.nbj7ikkuufy0@srmbuffer010210212018.sqa.ztt    |   File "/usr/local/lib/python3.6/site-packages/pymongo/database.py", line 439, in _command
mongo_controller.1.nbj7ikkuufy0@srmbuffer010210212018.sqa.ztt    |     client=self.__client)
mongo_controller.1.nbj7ikkuufy0@srmbuffer010210212018.sqa.ztt    |   File "/usr/local/lib/python3.6/site-packages/pymongo/pool.py", line 496, in command
mongo_controller.1.nbj7ikkuufy0@srmbuffer010210212018.sqa.ztt    |     collation=collation)
mongo_controller.1.nbj7ikkuufy0@srmbuffer010210212018.sqa.ztt    |   File "/usr/local/lib/python3.6/site-packages/pymongo/network.py", line 125, in command
mongo_controller.1.nbj7ikkuufy0@srmbuffer010210212018.sqa.ztt    |     parse_write_concern_error=parse_write_concern_error)
mongo_controller.1.nbj7ikkuufy0@srmbuffer010210212018.sqa.ztt    |   File "/usr/local/lib/python3.6/site-packages/pymongo/helpers.py", line 146, in _check_command_response
mongo_controller.1.nbj7ikkuufy0@srmbuffer010210212018.sqa.ztt    |     raise OperationFailure(msg % errmsg, code, response)
```

**Comment by buhe** [comment]
here, mongo client connect mongod from swarm vip found data inconsistencies

**Comment by chicco785** [comment]
hi,
would you be able to describe how to replicate the issue?

thx,
federico

**Comment by gentunian** [comment]
Any news on this issue? I was planning to give the project a try :)

**Comment by R-Hammer** [comment]
me too, have someone tried it with a newer mongodb version?

**Comment by chicco785** [comment]
we moved away from docker swarm to k8s, so the project is not maintained.
